### ISSUE TITLE
rss feed checker failing atm

### ISSUE THREAD

**Issue by ghost** [ckipp01/webring-checker#4]
i just updated my rss (yes, manually xD)
and wanted to check if it's gonna show up..

but there is an error:
> content.map is not a function

i'll look into it in the next hour or so, just wanted to report it first

**Comment by ckipp01** [comment]
Yea, thanks for the heads up. I believe I saw this before with your feed as well, but I thought I had fixed it. However, looking at it now my assumptions were wrong. I'm not 100% sure why, but it looks like my xml parser that I'm using is parsing your `<item>` as a single object rather than an array. I think this is because there is only one entry, so it assumes object. I'm curious if you'd add another if it would then return an array.

Either way, I see where the issue is, and I'll try to push a fix today for both this and the webring-cli.
